### ISSUE TITLE
error flutter 1.17.4

### ISSUE THREAD

**Issue by joset1ag0** [TheAlphamerc/flutter_wallet_app#1]
lib/src/widgets/customRoute.dart:9:18: Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring

**Comment by BoniWPy** [comment]
me too

**Comment by volvicoasis** [comment]
FYI      if (settings.name == '/') { https://stackoverflow.com/a/62459093

**Comment by emmaakachukwu** [comment]
Pull request for the fix https://github.com/TheAlphamerc/flutter_wallet_app/pull/2

**Comment by TheAlphamerc** [comment]
> Pull request for the fix #2

Thanks @emmaakachukwu for fixing the issue and making contribution to project.
